// <auto-generated />
namespace vChat.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EditFriendMap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditFriendMap));
        
        string IMigrationMetadata.Id
        {
            get { return "201304120857458_EditFriendMap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
